ScriptAlias /munin-cgi/munin-cgi-graph /usr/lib/munin/cgi/munin-cgi-graph
LogFormat "%{CF-Connecting-IP}i %h %l %u %t \"%r\" %>s %b" vhost_combined
Listen 8888

Alias / /var/cache/munin/www/

SetEnvIf CF-Connecting-IP "^2\.28\.232\.185$" let_me_in

<Directory /var/cache/munin/www>
    <RequireAny>
        # Allow entry if the environment variable was flagged above
        Require env let_me_in
        
        # Optional: Also allow localhost if you need to run internal CLI tools
        #Require ip 127.0.0.1
    </RequireAny>
</Directory>


#<Directory /var/cache/munin/www>
#        Require ip 2.28.232.185
#        #Require all granted
#</Directory>

<Location /munin-cgi/munin-cgi-graph>
        Options +ExecCGI
        AllowOverride None
        Require all granted
        <IfModule mod_fcgid.c>
            SetHandler fcgid-script
        </IfModule>
        <IfModule !mod_fcgid.c>
            SetHandler cgi-script
        </IfModule>
</Location>

<IfModule mod_remoteip_module>
    RemoteIPHeader CF-Connecting-IP
    # Trust Cloudflare's internal tunnel proxies
    RemoteIPTrustedProxy 172.17.0.2
    #RemoteIPTrustedProxy ::1
</IfModule>

#LogFormat "%{CF-Connecting-IP}i %h %l %u %t \"%r\" %>s %b" common
